version: '3.8'

services:
  app:
    image: download_liked_coubs
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/logs
    environment:
      - rerun_in_minutes = 1440
    ports:
      - "8000:8000"  
    environment:
      - PYTHONDONTWRITEBYTECODE = 1
      - PYTHONUNBUFFERED = 1
